---

- name: AWSCLI | Install prerequisites packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip

- name: AWSCLI | Install packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - awscli

- name: AWSCLI | Create directories
  become: yes
  become_user: "{{ item.username }}"
  file:
    state: directory
    path: ".aws"
    mode: 0750
  with_items: "{{ awscli }}"

- name: AWSCLI | Configuration
  become: yes
  become_user: "{{ item.username }}"
  template:
    src: "aws/config.j2"
    dest: ".aws/config"
    mode: 0500
  with_items: "{{ awscli }}"

- name: AWSCLI | Set credentials
  become: yes
  become_user: "{{ item.username }}"
  template:
    src: "aws/credentials.j2"
    dest: ".aws/credentials"
    mode: 0500
  with_items: "{{ awscli }}"
